warning : <%s> bad argument

warning : no custom tile specified

warning : no output file given

warning : <%s> unkown argument

warning : argument <%s> ignored

warning : what language do you want ?

(%s illegal move) 

(%s move not allowed : three paths case) 

traxfig [-v][-ps][-n][-l <messages>][-f <format>][-o { '=' | <ouput file> }]
 [ <input file> | <move sequence> ]
-v               : verbose
-ps              : postcript output (no verbose)
-n               : move detected when number followed by move notation
-f <format>      : drawing style of tiles
-o =             : output to file <input file name>.out or traxfig.out
-o <output file> : output to file <output file>
<move sequence>  : ex. "A1S 1AR B1U"
-l <message>     : error messages file (for foreign languages)
-a               : all tiles numbered (with numbered.tfm file)
-u               : generate www URL page
-i               : generate interactive URL
-t               : generate URL with tables
-g <game name>   : name of game -- "of Trax" is default
-w <white name>  : name of white player -- "White" is default
-b <black name>  : name of black player -- "Black" is default

traxfig, v:2.11, 20/09/1994, by Thierry Grellier, thanks to
Uwe G. Wilhelm and Richard Rognlie for PostScript output and
Soren Pingel Dalsgaard for HTML output.

%s $

.

Reading from %s : 

error : <%s> not opened

